#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := adc_example
IDF_PATH := /home/xu/esp/ESP8266_RTOS_SDK
include $(IDF_PATH)/make/project.mk

