#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := smart_config
IDF_PATH := /home/xu/esp/GraduationDesign
include $(IDF_PATH)/make/project.mk

